#!/bin/bash
#
# Docker Hub Automated Builds hook
#

for api_level in ${ANDROID_API[*]} ; do
  for build_tools in ${ANDROID_BUILD_TOOLS[*]} ; do
    ./scripts/docker/build \
      --android-api ${api_level} \
      --android-build-tools ${build_tools} \
      --docker-push
  done
done
