#!/bin/bash
#
# Docker Hub Automated Builds hook
#

for android in ${ANDROID_API[*]}; do
  for jdk in ${JDK[*]}; do
    ./scripts/build \
      --android "${android}" \
      --jdk "${jdk}" \
      --push
  done
done
