name: CI

on:
  push:
    branches: main
    paths: Dockerfile
  pull_request:
    branches: main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE: saschpe/android-sdk
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  buildx:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        jdk: [ 11.0.18_10, 17.0.6_10 ]
        android: [ 31, 32, 33 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.IMAGE }}
            ghcr.io/${{ env.IMAGE }}
          tags: |
            type=raw,value=${{ matrix.android }}-jdk${{ matrix.jdk }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to Github Container Repository
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            jdk=${{ matrix.jdk }} 
            android=${{ matrix.android }}
          provenance: true
          sbom: true
          cache-from: type=registry,ref=user/app:latest
          cache-to: type=inline
      - name: Update Docker Hub repository description
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.IMAGE }}
          short-description: ${{ github.event.repository.description }}